// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: schema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The top-level message containing the entire session flow
type HybridSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all recorded events (semantic + DOM snapshots)
	Events        []*HybridEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSession) Reset() {
	*x = HybridSession{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSession) ProtoMessage() {}

func (x *HybridSession) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSession.ProtoReflect.Descriptor instead.
func (*HybridSession) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *HybridSession) GetEvents() []*HybridEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type HybridEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source of the event: "custom" (semantic) or "rrweb" (DOM)
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Timestamp in epoch milliseconds (double to capture high precision if needed)
	Timestamp float64 `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event type: e.g., "click", "input", "tab_switch" OR rrweb event type (as string/int)
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// For custom events: specific action details (optional)
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// For input events: the value entered
	Value string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// Target element details for semantic events
	Target *CustomTarget `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	// For copy/paste/cut events: the text content involved
	Text string `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	// JSON-serialized string containing complex data
	// Used for:
	// - rrweb event payloads (full DOM snapshots, mutations)
	// - tab_switch details (url, title, id)
	Data          string `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridEvent) Reset() {
	*x = HybridEvent{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridEvent) ProtoMessage() {}

func (x *HybridEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridEvent.ProtoReflect.Descriptor instead.
func (*HybridEvent) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *HybridEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HybridEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HybridEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HybridEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HybridEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *HybridEvent) GetTarget() *CustomTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *HybridEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *HybridEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CustomTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CSS selector path to the element
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// HTML tag name (e.g., "BUTTON", "INPUT")
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// Rough text content of the element (for context/verification)
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomTarget) Reset() {
	*x = CustomTarget{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomTarget) ProtoMessage() {}

func (x *CustomTarget) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomTarget.ProtoReflect.Descriptor instead.
func (*CustomTarget) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *CustomTarget) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *CustomTarget) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CustomTarget) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\tbravebird\"?\n" +
	"\rHybridSession\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.bravebird.HybridEventR\x06events\"\xde\x01\n" +
	"\vHybridEvent\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12/\n" +
	"\x06target\x18\x06 \x01(\v2\x17.bravebird.CustomTargetR\x06target\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x12\n" +
	"\x04data\x18\b \x01(\tR\x04data\"P\n" +
	"\fCustomTarget\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textB/Z-dev/bravebird/browser-automation-go/pkg/protob\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_proto_goTypes = []any{
	(*HybridSession)(nil), // 0: bravebird.HybridSession
	(*HybridEvent)(nil),   // 1: bravebird.HybridEvent
	(*CustomTarget)(nil),  // 2: bravebird.CustomTarget
}
var file_schema_proto_depIdxs = []int32{
	1, // 0: bravebird.HybridSession.events:type_name -> bravebird.HybridEvent
	2, // 1: bravebird.HybridEvent.target:type_name -> bravebird.CustomTarget
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
